id: cov_awaddr_alignment
kind: coverage_code_creation
description_md: gym/tasks/cov_awaddr_alignment/description.md
allowed_edits:
  - src/hvl_top/master/**
  - src/hvl_top/test/**
  - src/hvl_top/test/sequences/**
  - src/hvl_top/test/virtual_sequences/**
eval:
  script: gym/eval/check_coverpoint_task.py
  args:
    - axi4_unaligned_awaddr_test
    - --coverpoint
    - AWADDR_ALIGNMENT_CP
    - --bins
    - UNALIGNED
    - --min_hits
    - "1"
